version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: hotel_management_db
    environment:
      POSTGRES_USER: nugraha
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hotel_management
    ports:
      - "5434 :5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
